import {
  US_ASSESSMENT_VERSION,
  USAssessmentAnswers,
} from "./schema";

export function createDefaultUSAssessmentAnswers(): USAssessmentAnswers {
  return {
    assessment_version: US_ASSESSMENT_VERSION,

    home: {
      zip_code: "",
      state: null,
      home_type: "Detached house",
      build_year_band: "1990-2009",
      home_size_band: "1,500-1,999",
      occupants: "3-4",
      foundation: "Concrete slab",
      garage_type: "No garage",
      rooms_above_or_beside_attached_garage: "N/A",
      windows: "Double-pane",
      window_age_band: "10-20",
      window_door_issues: [],
      sunny_window_coverings: "Mixture",
      closes_coverings_for_summer_sun: "Sometimes",
      rooms_consistently_hot_or_cold: "No",
      hot_or_cold_room_locations: [],
    },

    hvac: {
      main_heating: "Heat pump",
      main_cooling: "Heat pump",
      system_age_band: "5-10",
      thermostat_type: "Programmable",
      summer_setpoint_f: 76,
      winter_setpoint_f: 68,
      setback_when_away_or_sleeping: "Sometimes",
      filter_frequency: "Every 2-3 months",
      blocked_supply_or_return_vents: "No",
      duct_location: "Conditioned space",
      symptoms: [],
      ceiling_fan_use: "Sometimes",
      turns_off_fans_in_empty_rooms: "Usually",
      portable_space_heater_use: "Never",
      heat_pump_aux_heat_frequency: "N/A",
    },

    water_heating: {
      type: "Electric storage tank",
      age_band: "5-10",
      temperature_band: "Around 120F",
      showers_per_day: "3-4",
      shower_length: "5-10",
      showers_or_baths: "Showers",
      low_flow_showerheads: "Not sure",
      dripping_hot_water_fixtures: "No",
      long_hot_water_wait: "No",
      recirculation_pump: "No",
      accessible_hot_water_pipes_insulated: "Not sure",
      water_heater_location: "Utility room",
      runs_out_of_hot_water: "Never",
    },

    appliances: {
      refrigerators_in_regular_use: "1",
      extra_cold_storage_location: [],
      extra_cold_storage_age_band: null,
      other_cold_storage: [],
      clothes_dryer_type: "Electric dryer",
      dryer_loads_per_week: "3-5",
      multiple_drying_cycles: "Rarely",
      dishwasher_heated_dry: "Sometimes",
      dishwasher_frequency: "About 1/day",
      laundry_wash_temperature: "Mixed",
      partial_loads: "Rarely",
      main_cooking_equipment: ["Electric range"],
      high_use_computing_entertainment: [],
      work_from_home_frequency: "No",
      entertainment_left_on_unnecessarily: "Rarely",
      other_continuous_loads: [],
      outdoor_security_lighting: "Motion",
      electric_vehicle: "No",
      time_of_use_electricity_pricing: "Not sure",
    },

    outdoor: {
      swimming_pool: false,
      pool_pump_type: "N/A",
      pool_pump_runtime: "N/A",
      pool_heating: "N/A",
      pool_cover_use: "N/A",
      hot_tub_spa: false,
      hot_tub_use_frequency: null,
      hot_tub_cover: "N/A",
      hot_tub_kept_hot_continuously: "N/A",
      garage_equipment: [],
      garage_door_use: "N/A",
      outdoor_lighting_control: "Motion",
      landscape_lighting: "None",
      private_well: "No",
      well_pump_cycles_unusually_often: "N/A",
      irrigation_system: false,
      unusual_loads: [],
    },

    solar_battery_ev: {
      rooftop_solar: false,
      solar_size_kw: null,
      solar_install_year: null,
      solar_interest: "Maybe",
      roof_orientation: "Not sure",
      roof_shading: "Not sure",
      usable_roof_space: "Not sure",
      authority_to_install_solar: "Yes",
      home_battery_installed: false,
      battery_goal: "Not sure",
      ev_phev: "No",
      home_charging_type: "N/A",
      ev_charging_time: "N/A",
      cheaper_off_peak_ev_rate: "N/A",
    },

    bills_behaviour: {
      energy_sources: ["Electricity"],
      typical_monthly_electricity_bill: null,
      highest_electricity_bill: null,
      electricity_usage_kwh_monthly: null,
      electricity_usage_kwh_annual: null,
      electricity_unit_rate_per_kwh: null,
      natural_gas_typical_bill: null,
      natural_gas_therms: null,
      natural_gas_unit_rate_per_therm: null,
      propane_annual_spend: null,
      propane_gallons: null,
      propane_unit_rate_per_gallon: null,
      heating_oil_annual_spend: null,
      heating_oil_gallons: null,
      heating_oil_unit_rate_per_gallon: null,
      bills_highest: "Not sure",
      bills_increased_noticeably: "No",
      changes_when_bills_increased: [],
      daytime_occupancy: "Varies",
      occupied_year_round: "Yes",
      heats_or_cools_rarely_used_rooms: "No",
      doors_windows_open_while_hvac_runs: "Rarely",
      electricity_use_peak: "Not sure",
      time_of_use_pricing: "Not sure",
      known_peak_hours: null,
    },

    hidden_context: {
      climate_context: null,
      climate_source: null,
    },
  };
}
